apiVersion: "etcd.database.coreos.com/v1beta2"
kind: "EtcdCluster"
metadata:
  name: "cilium-etcd-operator"
  ## Adding this annotation make this cluster managed by clusterwide operators
  ## namespaced operators ignore it
  # annotations:
  #   etcd.database.coreos.com/scope: clusterwide
  namespace: kube-system
spec:
  size: 3
  version: "3.2.23"
  pod:
    labels:
      "io.cilium.fixed-identity": "kv-store"
